### ISSUE TITLE
Test SAC and LAC with new EX3_EKF_gyro environment

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/LAC-TF2-TORCH-translation#14]
Let's test the LAC and SAC algorithm with the new EX3_EKF_gyro environment. 

## TODOS

- [x] Train LAC on the new EX3_EKF_gyro environment.
- [x] Train SAC on the new EX3_EKF_gyro environment.
- [x] Compare the results.
